// TODO: Resolve import issue; [might be issue](https://svelte.dev/docs/kit/packaging#Anatomy-of-a-package.json-exports)
// ! Cannot find package 'bits-ui'
// import {
//   Accordion,
//   AlertDialog,
//   AspectRatio,
//   Avatar,
//   Button,
//   Calendar,
//   Checkbox,
//   Collapsible,
//   Combobox,
//   Command,
//   ContextMenu,
//   DateField,
//   DatePicker,
//   DateRangeField,
//   DateRangePicker,
//   Dialog,
//   DropdownMenu,
//   Label,
//   LinkPreview,
//   Menubar,
//   Meter,
//   NavigationMenu,
//   Pagination,
//   PinInput,
//   Popover,
//   Progress,
//   RadioGroup,
//   RangeCalendar,
//   ScrollArea,
//   Select,
//   Separator,
//   Slider,
//   Switch,
//   Tabs,
//   Toggle,
//   ToggleGroup,
//   Toolbar,
//   Tooltip
// } from "bits-ui";

export const components = {
  accordion: ["root", "item", "header", "trigger", "content"],
  alertDialog: ["root", "title", "action", "cancel", "content", "overlay", "trigger", "description"],
  aspectRatio: ["root"],
  avatar: ["root", "image", "fallback"],
  button: ["root"],
  calendar: [
    "root",
    "day",
    "grid",
    "gridBody",
    "cell",
    "gridHead",
    "headCell",
    "gridRow",
    "header",
    "heading",
    "nextButton",
    "prevButton"
  ],
  checkbox: ["root", "group", "groupLabel"],
  collapsible: ["root", "content", "trigger"],
  combobox: [
    "root",
    "input",
    "separator",
    "arrow",
    "trigger",
    "content",
    "contentStatic",
    "item",
    "group",
    "groupHeading",
    "viewport",
    "scrollDownButton",
    "scrollUpButton"
  ],
  command: [
    "root",
    "empty",
    "group",
    "groupHeading",
    "groupItems",
    "input",
    "item",
    "linkItem",
    "list",
    "viewport",
    "loading",
    "separator"
  ],
  contextMenu: [
    "root",
    "sub",
    "item",
    "group",
    "groupHeading",
    "arrow",
    "content",
    "contentStatic",
    "trigger",
    "radioItem",
    "separator",
    "radioGroup",
    "subContent",
    "subContentStatic",
    "subTrigger",
    "checkboxItem"
  ],
  dateField: ["root", "input", "label", "segment"],
  datePicker: ["root", "input", "label", "segment"],
  dateRangeField: ["root", "input", "label", "segment"],
  dateRangePicker: [
    "root",
    "calendar",
    "trigger",
    "content",
    "arrow",
    "close",
    "input",
    "label",
    "segment",
    "gridBody",
    "gridHead",
    "gridRow",
    "grid",
    "headCell",
    "header",
    "heading",
    "nextButton",
    "prevButton",
    "cell",
    "day"
  ],
  dialog: ["root", "title", "close", "content", "overlay", "trigger", "description"],
  dropdownMenu: [
    "root",
    "sub",
    "item",
    "group",
    "groupHeading",
    "arrow",
    "content",
    "contentStatic",
    "trigger",
    "radioItem",
    "separator",
    "radioGroup",
    "subContent",
    "subContentStatic",
    "subTrigger",
    "checkboxItem"
  ],
  label: ["root"],
  linkPreview: ["arrow", "root", "content", "trigger", "contentStatic"],
  menubar: [
    "root",
    "menu",
    "content",
    "contentStatic",
    "trigger",
    "sub",
    "item",
    "group",
    "groupHeading",
    "arrow",
    "radioItem",
    "separator",
    "subContent",
    "subContentStatic",
    "subTrigger",
    "radioGroup",
    "checkboxItem"
  ],
  meter: ["root"],
  navigationMenu: ["root", "content", "indicator", "item", "link", "list", "trigger", "viewport", "sub"],
  pagination: ["root", "prevButton", "nextButton", "page"],
  pinInput: ["root", "cell"],
  popover: ["root", "arrow", "content", "contentStatic", "trigger", "close"],
  progress: ["root"],
  radioGroup: ["root", "item"],
  rangeCalendar: [
    "root",
    "day",
    "cell",
    "grid",
    "gridBody",
    "gridHead",
    "headCell",
    "gridRow",
    "header",
    "heading",
    "nextButton",
    "prevButton"
  ],
  scrollArea: ["root", "viewport", "scrollbar", "thumb", "corner"],
  select: [
    "root",
    "content",
    "contentStatic",
    "item",
    "group",
    "groupHeading",
    "trigger",
    "viewport",
    "scrollUpButton",
    "scrollDownButton"
  ],
  separator: ["root"],
  slider: ["root", "range", "thumb", "tick"],
  switch: ["root", "thumb"],
  tabs: ["root", "content", "list", "trigger"],
  toggle: ["root"],
  toggleGroup: ["root", "item"],
  toolbar: ["root", "button", "link", "group", "groupItem"],
  tooltip: ["root", "content", "contentStatic", "trigger", "arrow", "provider"]
};
